version: '3'
services:

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - conf:/etc/nginx/conf.d:ro
      - vhost:/etc/nginx/vhost.d:ro
      - html:/usr/share/nginx/html:ro
      - /root/certs:/etc/nginx/certs:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true
      - com.github.helder.docker_gen.nginx_proxy=true
    restart: always

  dockergen:
    image: helder/docker-gen
    command: -notify "docker-label-sighup com.github.helder.docker_gen.nginx_proxy" -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - conf:/etc/nginx/conf.d:rw
      - vhost:/etc/nginx/vhost.d:rw
      - /root/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen=true
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - conf:/etc/nginx/conf.d:rw
      - vhost:/etc/nginx/vhost.d:rw
      - html:/usr/share/nginx/html:rw
      - /root/certs/:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory
    restart: always

volumes:
  conf:
  vhost:
  html:
